# Generated by Django 4.0.3 on 2022-03-30 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestno', models.CharField(max_length=100)),
                ('electiontype', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contestantid', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('status', models.BooleanField(default=False)),
                ('party', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contestno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evotingapp.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('FatherName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=20)),
                ('Aadhaar', models.CharField(max_length=12)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Points', models.IntegerField(default=0)),
                ('Contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evotingapp.contest')),
                ('Contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evotingapp.contestant')),
                ('Voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evotingapp.voter')),
            ],
        ),
    ]
