# Generated by Django 4.0.3 on 2022-04-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evotingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
